"""Profils clients de démonstration (low / medium / high risk)."""

DEMO_PROFILES = {
    "low": {
        "duration": 12,
        "credit_amount": 1500,
        "installment_commitment": 2,
        "residence_since": 4,
        "age": 45,
        "existing_credits": 1,
        "num_dependents": 1,
        "checking_status": "0<=X<200",
        "credit_history": "existing paid",
        "purpose": "radio/tv",
        "savings_status": ">=1000",
        "employment": ">=7",
        "personal_status": "male mar/wid",
        "other_parties": "none",
        "property_magnitude": "real estate",
        "other_payment_plans": "none",
        "housing": "own",
        "job": "skilled",
        "own_telephone": "yes",
        "foreign_worker": "yes",
    },
    "medium": {
        "duration": 24,
        "credit_amount": 5000,
        "installment_commitment": 3,
        "residence_since": 3,
        "age": 35,
        "existing_credits": 2,
        "num_dependents": 1,
        "checking_status": "0<=X<200",
        "credit_history": "existing paid",
        "purpose": "car (new)",
        "savings_status": "500<=X<1000",
        "employment": "4<=X<7",
        "personal_status": "female div/dep",
        "other_parties": "guarantor",
        "property_magnitude": "car",
        "other_payment_plans": "bank",
        "housing": "rent",
        "job": "unskilled resident",
        "own_telephone": "none",
        "foreign_worker": "yes",
    },
    "high": {
        "duration": 48,
        "credit_amount": 12000,
        "installment_commitment": 4,
        "residence_since": 1,
        "age": 23,
        "existing_credits": 3,
        "num_dependents": 2,
        "checking_status": "<0",
        "credit_history": "critical/other existing credit",
        "purpose": "education",
        "savings_status": "<100",
        "employment": "<1",
        "personal_status": "male single",
        "other_parties": "none",
        "property_magnitude": "no known property",
        "other_payment_plans": "stores",
        "housing": "rent",
        "job": "unemployed",
        "own_telephone": "none",
        "foreign_worker": "yes",
    },
}
