"""Profils clients de démonstration (low / medium / high risk)."""

DEMO_PROFILES = {
    "low": {
        "duration": 10,
        "credit_amount": 1418.0,
        "installment_commitment": 3,
        "residence_since": 2,
        "age": 35,
        "existing_credits": 1,
        "num_dependents": 1,
        "checking_status": "no checking",
        "credit_history": "existing paid",
        "purpose": "new car",
        "savings_status": "100<=X<500",
        "employment": "1<=X<4",
        "personal_status": "male single",
        "other_parties": "none",
        "property_magnitude": "real estate",
        "other_payment_plans": "none",
        "housing": "rent",
        "job": "unskilled resident",
        "own_telephone": "none",
        "foreign_worker": "no",
    },
    "medium": {
        "duration": 12,
        "credit_amount": 1318.0,
        "installment_commitment": 4,
        "residence_since": 4,
        "age": 54,
        "existing_credits": 1,
        "num_dependents": 1,
        "checking_status": "0<=X<200",
        "credit_history": "existing paid",
        "purpose": "new car",
        "savings_status": ">=1000",
        "employment": ">=7",
        "personal_status": "male single",
        "other_parties": "none",
        "property_magnitude": "real estate",
        "other_payment_plans": "none",
        "housing": "own",
        "job": "skilled",
        "own_telephone": "yes",
        "foreign_worker": "yes",
    },
    "high": {
        "duration": 12,
        "credit_amount": 709.0,
        "installment_commitment": 4,
        "residence_since": 4,
        "age": 57,
        "existing_credits": 1,
        "num_dependents": 1,
        "checking_status": "<0",
        "credit_history": "existing paid",
        "purpose": "radio/tv",
        "savings_status": "<100",
        "employment": ">=7",
        "personal_status": "male single",
        "other_parties": "none",
        "property_magnitude": "real estate",
        "other_payment_plans": "stores",
        "housing": "own",
        "job": "unskilled resident",
        "own_telephone": "none",
        "foreign_worker": "yes",
    },
}
